---
- name: Ensure config directory path exists
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  become_user: "{{ ansible_user }}"
  with_items:
    - "/home/{{ ansible_user }}/.config/nvim"
    - "/home/{{ ansible_user }}/.local/share/nvim/site/autoload/"

- name: Install neovim supporting packages
  apt:
    state: present
    name:
      - python-neovim
      - python3-neovim
      - git
      - silversearcher-ag
      - latexmk

- name: Get and install neovim appimage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.4.3/nvim.appimage
    dest: /usr/bin/nvim
    mode: 0755

- name: Get vim plug for neovim
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ ansible_user }}/.local/share/nvim/site/autoload/plug.vim"
  become: yes
  become_user: "{{ ansible_user }}"

- name: Copy neovim dot-config
  copy:
    src: init.vim
    dest: "/home/{{ ansible_user }}/.config/nvim/init.vim"
